#!/bin/bash

function start-parcel() { 

    function fatal() {
        CYAN='\033[0;36m'
        RED='\033[0;31m'
        NC='\033[0m'
        echo -e "$0: ${RED}Error:${CYAN} $@" >&2
        exit 0
    }

    function out() {
        CYAN='\033[0;36m'
        PURPLE='\033[0;35m'
        NC='\033[0m'
        echo -e "${CYAN}[parcel] ${PURPLE}$@${NC}"
    }
    
    local extract_parcel delete_parcels import_parcels help_needed uninstall  get_version get_location clean_opened list_parcels reset_pin PARCELS_FOLDER SOURCE targets_string

    extract_parcel=false
    delete_parcels=false
    import_parcels=false
    help_needed=false
    uninstall=false
    get_version=false
    get_location=false
    clean_opened=false
    list_parcels=false
    reset_pin=false
    display_options=false

    PARCELS_FOLDER="Parcels"
    SCRIPT_ABS_PATH=$(readlink -f "$0")
    SCRIPT_PATH="$(dirname $SCRIPT_ABS_PATH)"
    SOURCE="${SCRIPT_PATH}/src/_parcel.sh"
    targets_string=""

    source "${SCRIPT_PATH}/src/_init.sh"
    clear

    if [[ $# -eq 0 ]]; then
        display_options=true
    fi 

    #////// * GET OPTIONS * //////
    
    while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
        -x | --extract) # Open a .parcel archive.   
            extract_parcel=true
        ;;
        -c | --clean) # Remove any opened parcels. Opened-Parcels/
            clean_opened=true
        ;;
        -d | --delete) # Delete archived parcels from Parcels/.
            delete_parcels=true
        ;;
        -v | --version) # Get the current version.
            get_version=true
        ;;
        -h | --help) # Print options.
            help_needed=true
        ;;
        -l | --get-location) # Get the current location of the .parcel install folder.
            get_location=true
        ;;
        --uninstall) # Remove .parcel from your system.
            uninstall=true
        ;;  
        -i | --import) # Move external .parcel archives into parcels folder, Parcels/.
            import_parcels=true
        ;;
        --list) # List .parcel archives.
            list_parcels=true
        ;;
        --reset) # Resets pin used for parcel.
            reset_pin=true
        ;;
        \?)
            fatal "Invalid option: -$OPTARG"
        ;;
    esac; shift; done
    if [[ "$1" == '--' ]]; then shift; fi
    
    #////// * ADD TARGETS * //////
    for arg in "$@"; do
        # Note this outter clause will probably make it impossible to unarchive any .parcel files that are inside a parcel themselves.
        if [[ ! "$arg" == *.parcel ]]; then
            if [[ -e "$arg" ]]; then # if file/dir exists
                if [[ -f "$arg" ]]; then # if file
                    out "Processing file: $arg"
                    targets_string+="$arg "
                elif [[ -d "$arg" ]]; then # if dir
                    out "Processing folder: $arg"
                    targets_string+="$arg "
                fi
            else # invalid.
                out "File or folder not found: $arg"
                read -p ""
                exit 1
            fi
        else
            out "Target $arg is a .parcel archive."
        fi
    done

    #////// * DISPLAY OPTIONS * //////
    if [[ "$display_options" = true ]]; then
        source "${SCRIPT_PATH}/src/_help.sh"
        return 0
    fi

    #////// * EXTRACT PARCELS * //////
    if [[ "$extract_parcel" = true ]]; then
        source "${SCRIPT_PATH}/src/_open.sh"
        return 0
    fi

    #////// * DELETE PARCELS * //////
    if [[ "$delete_parcels" = true ]]; then
        source "${SCRIPT_PATH}/src/_del.sh"
        return 0    
    fi

    #////// * CLEAN OPENED PARCELS * //////
    if [[ "$clean_opened" = true ]]; then
        source "${SCRIPT_PATH}/src/_clean.sh"
        return 0
    fi

    #////// * IMPORT PARCELS * //////
    if [[ "$import_parcels" = true ]]; then
        source "${SCRIPT_PATH}/src/_import.sh"
        return 0
    fi

    #////// * PRINT HELP * //////
    if [[ "$help_needed" = true ]]; then
        source "${SCRIPT_PATH}/src/_help.sh"
        return 0
    fi

    #////// * UNINSTALL * //////
    if [[ "$uninstall" = true ]]; then
        source "${SCRIPT_PATH}/src/_uninstall.sh"
        return 0
    fi

    #////// * VERSION * //////
    if [[ "$get_version" = true ]]; then
        source "${SCRIPT_PATH}/src/_version.sh"
        return 0
    fi

    #////// * LOCATION * //////
    if [[ "$get_location" = true ]]; then
        source "${SCRIPT_PATH}/src/_location.sh"
        return 0
    fi

    #////// * LIST PARCELS * //////
    if [[ "$list_parcels" = true ]]; then
        source "${SCRIPT_PATH}/src/_list.sh"
        return 0
    fi

    #////// * RESET PIN * //////
    if [[ "$reset_pin" = true ]]; then
        source "${SCRIPT_PATH}/src/_reset.sh"
        return 0
    fi

    #////// * CREATE PARCEL * //////
    bash "$SOURCE" "$targets_string"
}

start-parcel "$@"

